// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCytJwi2HHgdmK2_BI7OFajUHG3YsRRq2c',
    appId: '1:344562318217:web:e4037c39190c161b9a7f58',
    messagingSenderId: '344562318217',
    projectId: 'sewa-kamera1',
    authDomain: 'sewa-kamera1.firebaseapp.com',
    storageBucket: 'sewa-kamera1.appspot.com',
    measurementId: 'G-NCMGN9MXRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPD11QjutTPOq7DWN_zTcA_NnF_qB3ZM',
    appId: '1:344562318217:android:fb1906240c952bca9a7f58',
    messagingSenderId: '344562318217',
    projectId: 'sewa-kamera1',
    storageBucket: 'sewa-kamera1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4w6Qgk9W7n36fLaKYrhkN0wqowG0n08',
    appId: '1:344562318217:ios:f8da489bc8b981929a7f58',
    messagingSenderId: '344562318217',
    projectId: 'sewa-kamera1',
    storageBucket: 'sewa-kamera1.appspot.com',
    iosBundleId: 'com.example.sewaKamera2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4w6Qgk9W7n36fLaKYrhkN0wqowG0n08',
    appId: '1:344562318217:ios:98f8f50012c68d189a7f58',
    messagingSenderId: '344562318217',
    projectId: 'sewa-kamera1',
    storageBucket: 'sewa-kamera1.appspot.com',
    iosBundleId: 'com.example.sewaKamera2.RunnerTests',
  );
}
